### ISSUE TITLE
Vote to raise Request Error exception on _make_request error?

### ISSUE THREAD

**Issue by Enuratique** [areed1192/td-ameritrade-python-api#81] opened 2020-07-31 05:40 UTC
https://github.com/areed1192/td-ameritrade-python-api/blob/aa732299b45899fcba623aef62723b4c51656b69/td/client.py#L558

I don't love that the _make_request function swallows errors and simply prints them to stdout. There are, on occasion, legitimate errors (edge cases in my case) that are thrown that my code needs to handle. The one in particular I'm thinking about is placing an order on an account with insufficient funds. Other errors I've seen crop up is when a token expires, but looking over the code, assuming you can refresh the access token in under 5 seconds, you shouldn't hit that error. But eventually the refresh token will expire while you have a valid session, and any requests made then will fail with an error.

Maybe instead of having the _make_request function implicitly return None, have it return the response.json() back? Or instead raise a custom exception with the error string in it?

It's still kind of shitty design on TD Ameritrade's part to not leverage specific error codes (or status codes) in their error strings, but you can at least parse the strings to handle different error conditions.

**Comment by FDoron** [comment] 2020-07-31 13:15
Agree. I am running into the same issues, for example handling errors caused by temporarily missing assets for short orders.

**Comment by areed1192** [comment] 2020-08-02 00:19
Hey guys, so this was addressed in an earlier issue and has been pushed to the main branch. For right now, you'll need to pull those changes. They will be pushed to the new package update when it happens. Thanks for the suggestion though 👍

**Closed** 2020-08-06 20:58 UTC
Labels: enhancement

**Comment by Enuratique** [comment] 2020-08-06 21:04
Any idea when a new version will be published to pip with these enhancements?
